---
title: "p8106_hw6_sn2863"
author: "Sydney Ng"
date: "11/24/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = .6,
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
homicide_df <-
  read_csv("./homicide-data.csv") %>%
  mutate(
    victim_age = as.numeric(victim_age),
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"      ~ 1
    )
  ) %>%
  filter(city_state != "Tulsa_AL",
         victim_race %in% c("Black", "White")) %>%
  select(city_state, resolved, victim_age, victim_race, victim_sex)

# by default, R will remove missing values (the whole row) when we want
# to run a regression model, unless we make it some unknown category...
```

Starting with one city
```{r}
baltimore_df <-
  homicide_df %>%
  filter(city_state == "Baltimore_MD")

glm(resolved ~ victim_age + victim_race + victim_sex,
    data = baltimore_df,
    family = binomial()) %>%
  broom::tidy() %>%
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96*std.error),
    CI_upper = exp(estimate + 1.96*std.error)
  ) %>%
  select(term, OR, starts_with("CI")) %>%
  knitr::kable(digits = 3)
```

Try this across different cities
```{r}
model_results_df <-
  homicide_df %>% 
  nest(data = -city_state) %>% # 3 cities do not report race and won't be included
  mutate(
    models = map(.x = data, 
                 ~glm(resolved ~ victim_age + victim_race + victim_sex,
                     data = .x,
                     family = binomial())),
    results = map(models, broom::tidy)
  ) %>%
  select(city_state, results) %>%
  unnest(results) %>%
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96*std.error),
    CI_upper = exp(estimate + 1.96*std.error)
  ) %>%
  select(term, OR, starts_with("CI"))
```

```{r}
model_results_df %>%
  filter(term == "victim_sexMale") %>%
  mutate(city_state = fct_reorder(city_state, OR)) %>%
  ggplot(aes(x=city_state, y=OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

### Problem 2 and 3 tips

```{r}
# child birthweight data for problem 2, deliberately open-ended
# use your best educated guess for the variables you decide to include your model
# you CAN do model selection, but maybe go more so for the literature...

# Two models, the first one is simple, the second with all the interactions 
# is a little more complicated...

# for the interaction term, you do not need to code for the main effect 
# -- you can JUST code for the interaction e.g. the three way interaction, 
# it will show you all the main AND the two-way interactions
# ^ check the screen cast!!

# workflow for cross-validation -- go back to the lecture maybe?
# looking at the residuals when cross-validating

# scatterplot with gestational period and birthweight
```

More about problem 3

```{r}
# central park weather dataset, getting rid of Waiki and Wtaerhole
# max temp and min temp scatterplot, we are interested in the r^2

# log(beta0*beta1)
# fit a model using the data and compute the adjusted r^2 using broom::glance()
# then use broom::tidy() to get all the coefficients to be able to multiply them
# AFTER you get the process, use bootstrapping
```


